spring:
  application:
    name: hbg
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/main?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: new password

token:
  access:
    secret: nklasndlksandksndksnasdnaskdnkasdnlkasdasdnasdklnas21312323132
    exprMin: 10
  refresh:
    secret: sdsadsadsadsadsaasdlmsadlmlsamsadlmsamdlsamdsadmsadknksadksand2113123
    exprHour: 6
    limtMin: 10
  aes256:
    key: "BES_AES_KEY@!#"
